services:
  order-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: order-api
        APP_PATH: apps/base/order-api
    env_file:
      - .env.fire-and-forget
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy

  fire-and-forget-inventory-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: fire-and-forget-inventory-worker
        APP_PATH: apps/fire-and-forget/inventory-worker
    env_file:
      - .env.fire-and-forget
    depends_on:
      rabbitmq:
        condition: service_healthy

  fire-and-forget-payment-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: fire-and-forget-payment-worker
        APP_PATH: apps/fire-and-forget/payment-worker
    env_file:
      - .env.fire-and-forget
    depends_on:
      rabbitmq:
        condition: service_healthy

  fire-and-forget-notification-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: fire-and-forget-notification-worker
        APP_PATH: apps/fire-and-forget/notification-worker
    env_file:
      - .env.fire-and-forget
    depends_on:
      rabbitmq:
        condition: service_healthy
