services:
  order-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: order-api
        APP_PATH: apps/base/order-api
    env_file:
      - .env.choreography-saga
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy

  choreography-saga-inventory-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: choreography-saga-inventory-worker
        APP_PATH: apps/choreography-saga/inventory-worker
    env_file:
      - .env.choreography-saga
    depends_on:
      rabbitmq:
        condition: service_healthy

  choreography-saga-payment-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: choreography-saga-payment-worker
        APP_PATH: apps/choreography-saga/payment-worker
    env_file:
      - .env.choreography-saga
    depends_on:
      rabbitmq:
        condition: service_healthy

  choreography-saga-shipping-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
      args:
        APP_NAME: choreography-saga-shipping-worker
        APP_PATH: apps/choreography-saga/shipping-worker
    env_file:
      - .env.choreography-saga
    depends_on:
      rabbitmq:
        condition: service_healthy
