FROM node:20-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

FROM deps AS builder
ARG APP_NAME
RUN npx nx build ${APP_NAME}

FROM node:20-alpine
ARG APP_PATH
WORKDIR /app
COPY --from=builder /app/dist/${APP_PATH} ./
COPY --from=deps /app/node_modules ./node_modules
CMD ["node", "main.js"]
